# docker-compose.yml
version: '3.9'

services:
  b2sync:
    image: b2sync:dev
    build:
      context: .
      dockerfile: src/b2sync/Dockerfile
    environment:
      - KEY_ID=TODO
      - APPLICATION_KEY=TODO
      - SOURCE_DIR=TODO
      - TARGET_BUCKET=jleblancBackupTimeMachine2
      - TARGET_PATH=TimeMachineBackups
    logging:
      driver: syslog
      options:
        syslog-address: "udp://nas.local:514"
        syslog-format: rfc3164
        labels: b2sync
        tag: "{{.Name}}-{{.ID}}"
